import {Box} from "@mui/material";
import {ReactNode} from "react";
import Head from "next/head";

export const Layout = ({children}: { children: ReactNode }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Box sx={{
                    height: "100dvh",
                    width: "100%",
                    padding: 2

                }}>
                    <Box sx={{
                        maxWidth: "1000px",
                        margin: "auto",
                    }}>
                        {children}
                    </Box>
                </Box>
            </main>
        </>
    )
}